# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QRadioButton, QSizePolicy, QStackedWidget, QTextEdit,
    QWidget)

class Ui_MAIN(object):
    def setupUi(self, MAIN):
        if not MAIN.objectName():
            MAIN.setObjectName(u"MAIN")
        MAIN.resize(1300, 800)
        MAIN.setMinimumSize(QSize(1300, 800))
        MAIN.setMaximumSize(QSize(1300, 800))
        MAIN.setStyleSheet(u"")
        self.centralwidget = QWidget(MAIN)
        self.centralwidget.setObjectName(u"centralwidget")
        self.home_pushButton = QPushButton(self.centralwidget)
        self.home_pushButton.setObjectName(u"home_pushButton")
        self.home_pushButton.setGeometry(QRect(5, 10, 141, 61))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(26)
        font.setBold(True)
        self.home_pushButton.setFont(font)
        self.home_pushButton.setStyleSheet(u"\n"
"background:rgb(255, 255, 255)\n"
"")
        self.calibrate_pushButton = QPushButton(self.centralwidget)
        self.calibrate_pushButton.setObjectName(u"calibrate_pushButton")
        self.calibrate_pushButton.setGeometry(QRect(180, 10, 141, 61))
        self.calibrate_pushButton.setFont(font)
        self.calibrate_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.test_pushButton = QPushButton(self.centralwidget)
        self.test_pushButton.setObjectName(u"test_pushButton")
        self.test_pushButton.setGeometry(QRect(350, 10, 141, 61))
        self.test_pushButton.setFont(font)
        self.test_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.setting_pushButton = QPushButton(self.centralwidget)
        self.setting_pushButton.setObjectName(u"setting_pushButton")
        self.setting_pushButton.setGeometry(QRect(1155, 10, 141, 61))
        self.setting_pushButton.setFont(font)
        self.setting_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(5, 79, 1290, 711))
        self.stackedWidget.setStyleSheet(u"")
        self.home_page = QWidget()
        self.home_page.setObjectName(u"home_page")
        self.home_page.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.message_1_label = QLabel(self.home_page)
        self.message_1_label.setObjectName(u"message_1_label")
        self.message_1_label.setGeometry(QRect(10, 0, 541, 91))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(48)
        font1.setBold(True)
        self.message_1_label.setFont(font1)
        self.message_1_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.message_2_label = QLabel(self.home_page)
        self.message_2_label.setObjectName(u"message_2_label")
        self.message_2_label.setGeometry(QRect(90, 70, 401, 71))
        self.message_2_label.setFont(font1)
        self.message_2_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.picture_label = QLabel(self.home_page)
        self.picture_label.setObjectName(u"picture_label")
        self.picture_label.setGeometry(QRect(390, 10, 891, 691))
        self.picture_label.setFont(font1)
        self.picture_label.setStyleSheet(u"border-image: url(picture/main_frame.png)\n"
"")
        self.picture_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stackedWidget.addWidget(self.home_page)
        self.picture_label.raise_()
        self.message_1_label.raise_()
        self.message_2_label.raise_()
        self.calibrate_page = QWidget()
        self.calibrate_page.setObjectName(u"calibrate_page")
        self.calibrate_page.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.r_weight_y_label = QLabel(self.calibrate_page)
        self.r_weight_y_label.setObjectName(u"r_weight_y_label")
        self.r_weight_y_label.setGeometry(QRect(20, 60, 131, 41))
        font2 = QFont()
        font2.setFamilies([u"TH Niramit AS"])
        font2.setPointSize(22)
        font2.setBold(True)
        self.r_weight_y_label.setFont(font2)
        self.r_weight_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.r_weight_x_label = QLabel(self.calibrate_page)
        self.r_weight_x_label.setObjectName(u"r_weight_x_label")
        self.r_weight_x_label.setGeometry(QRect(20, 140, 131, 41))
        self.r_weight_x_label.setFont(font2)
        self.r_weight_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.r_weight_y_lineEdit = QLineEdit(self.calibrate_page)
        self.r_weight_y_lineEdit.setObjectName(u"r_weight_y_lineEdit")
        self.r_weight_y_lineEdit.setGeometry(QRect(170, 60, 141, 51))
        font3 = QFont()
        font3.setFamilies([u"TH Niramit AS"])
        font3.setPointSize(24)
        font3.setBold(True)
        self.r_weight_y_lineEdit.setFont(font3)
        self.r_weight_y_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.r_weight_y_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.r_weight_x_lineEdit = QLineEdit(self.calibrate_page)
        self.r_weight_x_lineEdit.setObjectName(u"r_weight_x_lineEdit")
        self.r_weight_x_lineEdit.setGeometry(QRect(170, 140, 141, 51))
        self.r_weight_x_lineEdit.setFont(font3)
        self.r_weight_x_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.r_weight_x_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cl_background_labe = QLabel(self.calibrate_page)
        self.cl_background_labe.setObjectName(u"cl_background_labe")
        self.cl_background_labe.setGeometry(QRect(-10, 0, 1301, 711))
        self.cl_background_labe.setFont(font2)
        self.cl_background_labe.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.r_kg_y_label = QLabel(self.calibrate_page)
        self.r_kg_y_label.setObjectName(u"r_kg_y_label")
        self.r_kg_y_label.setGeometry(QRect(330, 70, 31, 41))
        self.r_kg_y_label.setFont(font2)
        self.r_kg_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.r_kg_x__label = QLabel(self.calibrate_page)
        self.r_kg_x__label.setObjectName(u"r_kg_x__label")
        self.r_kg_x__label.setGeometry(QRect(330, 140, 31, 41))
        self.r_kg_x__label.setFont(font2)
        self.r_kg_x__label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.c_weight_x_label = QLabel(self.calibrate_page)
        self.c_weight_x_label.setObjectName(u"c_weight_x_label")
        self.c_weight_x_label.setGeometry(QRect(20, 340, 131, 41))
        self.c_weight_x_label.setFont(font2)
        self.c_weight_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.c_kg_x__label = QLabel(self.calibrate_page)
        self.c_kg_x__label.setObjectName(u"c_kg_x__label")
        self.c_kg_x__label.setGeometry(QRect(330, 340, 31, 41))
        self.c_kg_x__label.setFont(font2)
        self.c_kg_x__label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.c_kg_y_label = QLabel(self.calibrate_page)
        self.c_kg_y_label.setObjectName(u"c_kg_y_label")
        self.c_kg_y_label.setGeometry(QRect(330, 270, 31, 41))
        self.c_kg_y_label.setFont(font2)
        self.c_kg_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.c_weight_y_lineEdit = QLineEdit(self.calibrate_page)
        self.c_weight_y_lineEdit.setObjectName(u"c_weight_y_lineEdit")
        self.c_weight_y_lineEdit.setGeometry(QRect(170, 260, 141, 51))
        self.c_weight_y_lineEdit.setFont(font3)
        self.c_weight_y_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.c_weight_y_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.c_weight_y_label = QLabel(self.calibrate_page)
        self.c_weight_y_label.setObjectName(u"c_weight_y_label")
        self.c_weight_y_label.setGeometry(QRect(20, 260, 131, 41))
        self.c_weight_y_label.setFont(font2)
        self.c_weight_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.c_weight_x_lineEdit = QLineEdit(self.calibrate_page)
        self.c_weight_x_lineEdit.setObjectName(u"c_weight_x_lineEdit")
        self.c_weight_x_lineEdit.setGeometry(QRect(170, 340, 141, 51))
        self.c_weight_x_lineEdit.setFont(font3)
        self.c_weight_x_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.c_weight_x_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cl_line = QFrame(self.calibrate_page)
        self.cl_line.setObjectName(u"cl_line")
        self.cl_line.setGeometry(QRect(0, 200, 370, 2))
        self.cl_line.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line.setFrameShape(QFrame.Shape.HLine)
        self.cl_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.cl_line_2 = QFrame(self.calibrate_page)
        self.cl_line_2.setObjectName(u"cl_line_2")
        self.cl_line_2.setGeometry(QRect(370, 5, 2, 497))
        self.cl_line_2.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_2.setFrameShape(QFrame.Shape.VLine)
        self.cl_line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.cl_line_3 = QFrame(self.calibrate_page)
        self.cl_line_3.setObjectName(u"cl_line_3")
        self.cl_line_3.setGeometry(QRect(0, 5, 370, 2))
        self.cl_line_3.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_3.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.cl_line_4 = QFrame(self.calibrate_page)
        self.cl_line_4.setObjectName(u"cl_line_4")
        self.cl_line_4.setGeometry(QRect(0, 400, 370, 2))
        self.cl_line_4.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_4.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.r_weight_label = QLabel(self.calibrate_page)
        self.r_weight_label.setObjectName(u"r_weight_label")
        self.r_weight_label.setGeometry(QRect(90, 10, 201, 41))
        self.r_weight_label.setFont(font2)
        self.r_weight_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.r_weight_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cl_line_5 = QFrame(self.calibrate_page)
        self.cl_line_5.setObjectName(u"cl_line_5")
        self.cl_line_5.setGeometry(QRect(0, 50, 370, 2))
        self.cl_line_5.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_5.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.cl_line_6 = QFrame(self.calibrate_page)
        self.cl_line_6.setObjectName(u"cl_line_6")
        self.cl_line_6.setGeometry(QRect(0, 250, 370, 2))
        self.cl_line_6.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_6.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.c_weight_label = QLabel(self.calibrate_page)
        self.c_weight_label.setObjectName(u"c_weight_label")
        self.c_weight_label.setGeometry(QRect(90, 210, 201, 41))
        self.c_weight_label.setFont(font2)
        self.c_weight_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.c_weight_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cl_set_zero_pushButton = QPushButton(self.calibrate_page)
        self.cl_set_zero_pushButton.setObjectName(u"cl_set_zero_pushButton")
        self.cl_set_zero_pushButton.setGeometry(QRect(10, 420, 161, 61))
        self.cl_set_zero_pushButton.setFont(font3)
        self.cl_set_zero_pushButton.setStyleSheet(u"background:rgb(85, 170, 127)")
        self.cl_calibrate_pushButton = QPushButton(self.calibrate_page)
        self.cl_calibrate_pushButton.setObjectName(u"cl_calibrate_pushButton")
        self.cl_calibrate_pushButton.setGeometry(QRect(200, 420, 161, 61))
        self.cl_calibrate_pushButton.setFont(font3)
        self.cl_calibrate_pushButton.setStyleSheet(u"background:rgb(0, 85, 127)")
        self.line = QFrame(self.calibrate_page)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 500, 370, 2))
        self.line.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.dis_set_zero_x_unit_label = QLabel(self.calibrate_page)
        self.dis_set_zero_x_unit_label.setObjectName(u"dis_set_zero_x_unit_label")
        self.dis_set_zero_x_unit_label.setGeometry(QRect(680, 140, 51, 41))
        self.dis_set_zero_x_unit_label.setFont(font2)
        self.dis_set_zero_x_unit_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.dis_set_zero_y_unit_label = QLabel(self.calibrate_page)
        self.dis_set_zero_y_unit_label.setObjectName(u"dis_set_zero_y_unit_label")
        self.dis_set_zero_y_unit_label.setGeometry(QRect(680, 70, 51, 41))
        self.dis_set_zero_y_unit_label.setFont(font2)
        self.dis_set_zero_y_unit_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.line_2 = QFrame(self.calibrate_page)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(370, 280, 370, 2))
        self.line_2.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.dis_set_zero_x_label = QLabel(self.calibrate_page)
        self.dis_set_zero_x_label.setObjectName(u"dis_set_zero_x_label")
        self.dis_set_zero_x_label.setGeometry(QRect(390, 140, 131, 41))
        self.dis_set_zero_x_label.setFont(font2)
        self.dis_set_zero_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.save_offset_pushButton = QPushButton(self.calibrate_page)
        self.save_offset_pushButton.setObjectName(u"save_offset_pushButton")
        self.save_offset_pushButton.setGeometry(QRect(570, 210, 161, 61))
        self.save_offset_pushButton.setFont(font3)
        self.save_offset_pushButton.setStyleSheet(u"background:rgb(255, 128, 130)")
        self.dis_set_zero_y_label = QLabel(self.calibrate_page)
        self.dis_set_zero_y_label.setObjectName(u"dis_set_zero_y_label")
        self.dis_set_zero_y_label.setGeometry(QRect(390, 60, 131, 41))
        self.dis_set_zero_y_label.setFont(font2)
        self.dis_set_zero_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.cl_line_8 = QFrame(self.calibrate_page)
        self.cl_line_8.setObjectName(u"cl_line_8")
        self.cl_line_8.setGeometry(QRect(370, 200, 370, 2))
        self.cl_line_8.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_8.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.dis_set_offset_y_lineEdit = QLineEdit(self.calibrate_page)
        self.dis_set_offset_y_lineEdit.setObjectName(u"dis_set_offset_y_lineEdit")
        self.dis_set_offset_y_lineEdit.setGeometry(QRect(520, 60, 141, 51))
        self.dis_set_offset_y_lineEdit.setFont(font3)
        self.dis_set_offset_y_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.dis_set_offset_y_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cl_line_10 = QFrame(self.calibrate_page)
        self.cl_line_10.setObjectName(u"cl_line_10")
        self.cl_line_10.setGeometry(QRect(370, 5, 370, 2))
        self.cl_line_10.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_10.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.cl_line_11 = QFrame(self.calibrate_page)
        self.cl_line_11.setObjectName(u"cl_line_11")
        self.cl_line_11.setGeometry(QRect(370, 50, 370, 2))
        self.cl_line_11.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_11.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.cl_line_12 = QFrame(self.calibrate_page)
        self.cl_line_12.setObjectName(u"cl_line_12")
        self.cl_line_12.setGeometry(QRect(740, 5, 2, 277))
        self.cl_line_12.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_12.setFrameShape(QFrame.Shape.VLine)
        self.cl_line_12.setFrameShadow(QFrame.Shadow.Sunken)
        self.dis_set_offset_x_lineEdit = QLineEdit(self.calibrate_page)
        self.dis_set_offset_x_lineEdit.setObjectName(u"dis_set_offset_x_lineEdit")
        self.dis_set_offset_x_lineEdit.setGeometry(QRect(520, 140, 141, 51))
        self.dis_set_offset_x_lineEdit.setFont(font3)
        self.dis_set_offset_x_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.dis_set_offset_x_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.r_weight_label_2 = QLabel(self.calibrate_page)
        self.r_weight_label_2.setObjectName(u"r_weight_label_2")
        self.r_weight_label_2.setGeometry(QRect(460, 10, 201, 41))
        self.r_weight_label_2.setFont(font2)
        self.r_weight_label_2.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.r_weight_label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.set_offset_pushButton = QPushButton(self.calibrate_page)
        self.set_offset_pushButton.setObjectName(u"set_offset_pushButton")
        self.set_offset_pushButton.setGeometry(QRect(380, 210, 161, 61))
        self.set_offset_pushButton.setFont(font3)
        self.set_offset_pushButton.setStyleSheet(u"background:rgb(187, 255, 144)")
        self.cl_line_13 = QFrame(self.calibrate_page)
        self.cl_line_13.setObjectName(u"cl_line_13")
        self.cl_line_13.setGeometry(QRect(370, 280, 370, 2))
        self.cl_line_13.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_13.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_13.setFrameShadow(QFrame.Shadow.Sunken)
        self.cl_line_14 = QFrame(self.calibrate_page)
        self.cl_line_14.setObjectName(u"cl_line_14")
        self.cl_line_14.setGeometry(QRect(370, 325, 370, 2))
        self.cl_line_14.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_14.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_14.setFrameShadow(QFrame.Shadow.Sunken)
        self.cl_line_15 = QFrame(self.calibrate_page)
        self.cl_line_15.setObjectName(u"cl_line_15")
        self.cl_line_15.setGeometry(QRect(740, 280, 2, 140))
        self.cl_line_15.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_15.setFrameShape(QFrame.Shape.VLine)
        self.cl_line_15.setFrameShadow(QFrame.Shadow.Sunken)
        self.cl_line_16 = QFrame(self.calibrate_page)
        self.cl_line_16.setObjectName(u"cl_line_16")
        self.cl_line_16.setGeometry(QRect(370, 418, 370, 2))
        self.cl_line_16.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.cl_line_16.setFrameShape(QFrame.Shape.HLine)
        self.cl_line_16.setFrameShadow(QFrame.Shadow.Sunken)
        self.set_zero_dx_pushButton = QPushButton(self.calibrate_page)
        self.set_zero_dx_pushButton.setObjectName(u"set_zero_dx_pushButton")
        self.set_zero_dx_pushButton.setGeometry(QRect(570, 340, 161, 61))
        self.set_zero_dx_pushButton.setFont(font3)
        self.set_zero_dx_pushButton.setStyleSheet(u"background:rgb(0, 255, 255)")
        self.set_zero_dy_pushButton = QPushButton(self.calibrate_page)
        self.set_zero_dy_pushButton.setObjectName(u"set_zero_dy_pushButton")
        self.set_zero_dy_pushButton.setGeometry(QRect(380, 340, 161, 61))
        self.set_zero_dy_pushButton.setFont(font3)
        self.set_zero_dy_pushButton.setStyleSheet(u"background:rgb(85, 170, 127)")
        self.r_weight_label_3 = QLabel(self.calibrate_page)
        self.r_weight_label_3.setObjectName(u"r_weight_label_3")
        self.r_weight_label_3.setGeometry(QRect(460, 285, 201, 41))
        self.r_weight_label_3.setFont(font2)
        self.r_weight_label_3.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.r_weight_label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stackedWidget.addWidget(self.calibrate_page)
        self.cl_background_labe.raise_()
        self.r_weight_label_3.raise_()
        self.r_weight_label_2.raise_()
        self.r_weight_y_label.raise_()
        self.r_weight_x_label.raise_()
        self.r_weight_y_lineEdit.raise_()
        self.r_weight_x_lineEdit.raise_()
        self.r_kg_y_label.raise_()
        self.r_kg_x__label.raise_()
        self.c_weight_x_label.raise_()
        self.c_kg_x__label.raise_()
        self.c_kg_y_label.raise_()
        self.c_weight_y_lineEdit.raise_()
        self.c_weight_y_label.raise_()
        self.c_weight_x_lineEdit.raise_()
        self.cl_line.raise_()
        self.cl_line_2.raise_()
        self.cl_line_3.raise_()
        self.cl_line_4.raise_()
        self.r_weight_label.raise_()
        self.cl_line_5.raise_()
        self.c_weight_label.raise_()
        self.cl_line_6.raise_()
        self.cl_set_zero_pushButton.raise_()
        self.cl_calibrate_pushButton.raise_()
        self.line.raise_()
        self.dis_set_zero_x_unit_label.raise_()
        self.dis_set_zero_y_unit_label.raise_()
        self.line_2.raise_()
        self.dis_set_zero_x_label.raise_()
        self.save_offset_pushButton.raise_()
        self.dis_set_zero_y_label.raise_()
        self.cl_line_8.raise_()
        self.dis_set_offset_y_lineEdit.raise_()
        self.cl_line_10.raise_()
        self.cl_line_11.raise_()
        self.cl_line_12.raise_()
        self.dis_set_offset_x_lineEdit.raise_()
        self.set_offset_pushButton.raise_()
        self.cl_line_13.raise_()
        self.cl_line_14.raise_()
        self.cl_line_15.raise_()
        self.cl_line_16.raise_()
        self.set_zero_dx_pushButton.raise_()
        self.set_zero_dy_pushButton.raise_()
        self.test_page = QWidget()
        self.test_page.setObjectName(u"test_page")
        self.test_page.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.test_background_label = QLabel(self.test_page)
        self.test_background_label.setObjectName(u"test_background_label")
        self.test_background_label.setGeometry(QRect(-20, -10, 1331, 751))
        self.test_background_label.setAutoFillBackground(False)
        self.test_background_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_weight_y_label = QLabel(self.test_page)
        self.test_weight_y_label.setObjectName(u"test_weight_y_label")
        self.test_weight_y_label.setGeometry(QRect(10, 20, 101, 51))
        self.test_weight_y_label.setFont(font3)
        self.test_weight_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_weight_y_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_weight_x_label = QLabel(self.test_page)
        self.test_weight_x_label.setObjectName(u"test_weight_x_label")
        self.test_weight_x_label.setGeometry(QRect(320, 20, 101, 51))
        self.test_weight_x_label.setFont(font3)
        self.test_weight_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_weight_x_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_dis_x_label = QLabel(self.test_page)
        self.test_dis_x_label.setObjectName(u"test_dis_x_label")
        self.test_dis_x_label.setGeometry(QRect(940, 20, 161, 51))
        self.test_dis_x_label.setFont(font3)
        self.test_dis_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_dis_x_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_dis_y_label = QLabel(self.test_page)
        self.test_dis_y_label.setObjectName(u"test_dis_y_label")
        self.test_dis_y_label.setGeometry(QRect(620, 20, 131, 51))
        self.test_dis_y_label.setFont(font3)
        self.test_dis_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_dis_y_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_weight_y_lineEdit = QLineEdit(self.test_page)
        self.test_weight_y_lineEdit.setObjectName(u"test_weight_y_lineEdit")
        self.test_weight_y_lineEdit.setGeometry(QRect(110, 20, 141, 51))
        self.test_weight_y_lineEdit.setFont(font3)
        self.test_weight_y_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.test_weight_y_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_weight_x_lineEdit = QLineEdit(self.test_page)
        self.test_weight_x_lineEdit.setObjectName(u"test_weight_x_lineEdit")
        self.test_weight_x_lineEdit.setGeometry(QRect(420, 20, 141, 51))
        self.test_weight_x_lineEdit.setFont(font3)
        self.test_weight_x_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.test_weight_x_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_dis_y_lineEdit = QLineEdit(self.test_page)
        self.test_dis_y_lineEdit.setObjectName(u"test_dis_y_lineEdit")
        self.test_dis_y_lineEdit.setGeometry(QRect(750, 20, 141, 51))
        self.test_dis_y_lineEdit.setFont(font3)
        self.test_dis_y_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.test_dis_y_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_dis_x_lineEdit = QLineEdit(self.test_page)
        self.test_dis_x_lineEdit.setObjectName(u"test_dis_x_lineEdit")
        self.test_dis_x_lineEdit.setGeometry(QRect(1100, 20, 141, 51))
        self.test_dis_x_lineEdit.setFont(font3)
        self.test_dis_x_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.test_dis_x_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_1line = QFrame(self.test_page)
        self.test_1line.setObjectName(u"test_1line")
        self.test_1line.setGeometry(QRect(0, 80, 1300, 2))
        self.test_1line.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.test_1line.setFrameShape(QFrame.Shape.HLine)
        self.test_1line.setFrameShadow(QFrame.Shadow.Sunken)
        self.grap_frame = QFrame(self.test_page)
        self.grap_frame.setObjectName(u"grap_frame")
        self.grap_frame.setGeometry(QRect(10, 90, 1071, 611))
        self.grap_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.grap_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.test_output_textEdit = QTextEdit(self.grap_frame)
        self.test_output_textEdit.setObjectName(u"test_output_textEdit")
        self.test_output_textEdit.setGeometry(QRect(0, 0, 1071, 631))
        self.test_output_textEdit.setFont(font3)
        self.test_start_pushButton = QPushButton(self.test_page)
        self.test_start_pushButton.setObjectName(u"test_start_pushButton")
        self.test_start_pushButton.setGeometry(QRect(1110, 190, 161, 61))
        font4 = QFont()
        font4.setFamilies([u"TH Niramit AS"])
        font4.setPointSize(28)
        font4.setBold(True)
        self.test_start_pushButton.setFont(font4)
        self.test_start_pushButton.setStyleSheet(u"background:rgb(155, 221, 163)")
        self.test_stop_pushButton = QPushButton(self.test_page)
        self.test_stop_pushButton.setObjectName(u"test_stop_pushButton")
        self.test_stop_pushButton.setGeometry(QRect(1110, 270, 161, 61))
        self.test_stop_pushButton.setFont(font4)
        self.test_stop_pushButton.setStyleSheet(u"background:rgb(255, 61, 2)")
        self.test_clear_pushButton = QPushButton(self.test_page)
        self.test_clear_pushButton.setObjectName(u"test_clear_pushButton")
        self.test_clear_pushButton.setGeometry(QRect(1110, 350, 161, 61))
        self.test_clear_pushButton.setFont(font4)
        self.test_clear_pushButton.setStyleSheet(u"background:rgb(0, 170, 255)")
        self.test_save_pushButton = QPushButton(self.test_page)
        self.test_save_pushButton.setObjectName(u"test_save_pushButton")
        self.test_save_pushButton.setGeometry(QRect(1110, 430, 161, 61))
        self.test_save_pushButton.setFont(font4)
        self.test_save_pushButton.setStyleSheet(u"background:rgb(170, 255, 255)")
        self.test_cyclic_round_label = QLabel(self.test_page)
        self.test_cyclic_round_label.setObjectName(u"test_cyclic_round_label")
        self.test_cyclic_round_label.setGeometry(QRect(1120, 80, 131, 51))
        self.test_cyclic_round_label.setFont(font3)
        self.test_cyclic_round_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_cyclic_round_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_cyclic_round_lineEdit = QLineEdit(self.test_page)
        self.test_cyclic_round_lineEdit.setObjectName(u"test_cyclic_round_lineEdit")
        self.test_cyclic_round_lineEdit.setGeometry(QRect(1120, 130, 141, 51))
        self.test_cyclic_round_lineEdit.setFont(font3)
        self.test_cyclic_round_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.test_cyclic_round_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.m_up_pushButton = QPushButton(self.test_page)
        self.m_up_pushButton.setObjectName(u"m_up_pushButton")
        self.m_up_pushButton.setGeometry(QRect(1160, 570, 60, 40))
        self.m_up_pushButton.setStyleSheet(u"background:rgb(85, 255, 0)")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoUp))
        self.m_up_pushButton.setIcon(icon)
        self.m_up_pushButton.setIconSize(QSize(35, 35))
        self.m_down_pushButton = QPushButton(self.test_page)
        self.m_down_pushButton.setObjectName(u"m_down_pushButton")
        self.m_down_pushButton.setGeometry(QRect(1160, 650, 60, 40))
        self.m_down_pushButton.setStyleSheet(u"background:rgb(85, 255, 0)")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoDown))
        self.m_down_pushButton.setIcon(icon1)
        self.m_down_pushButton.setIconSize(QSize(35, 35))
        self.m_out_pushButton = QPushButton(self.test_page)
        self.m_out_pushButton.setObjectName(u"m_out_pushButton")
        self.m_out_pushButton.setGeometry(QRect(1100, 610, 60, 40))
        self.m_out_pushButton.setStyleSheet(u"background:rgb(85, 170, 255)")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoPrevious))
        self.m_out_pushButton.setIcon(icon2)
        self.m_out_pushButton.setIconSize(QSize(35, 35))
        self.m_in_pushButton = QPushButton(self.test_page)
        self.m_in_pushButton.setObjectName(u"m_in_pushButton")
        self.m_in_pushButton.setGeometry(QRect(1220, 610, 60, 40))
        self.m_in_pushButton.setStyleSheet(u"background:rgb(85, 170, 255)")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoNext))
        self.m_in_pushButton.setIcon(icon3)
        self.m_in_pushButton.setIconSize(QSize(35, 35))
        self.m_stop_all_pushButton = QPushButton(self.test_page)
        self.m_stop_all_pushButton.setObjectName(u"m_stop_all_pushButton")
        self.m_stop_all_pushButton.setGeometry(QRect(1160, 610, 60, 40))
        self.m_stop_all_pushButton.setStyleSheet(u"background:rgb(255, 145, 137)")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackPause))
        self.m_stop_all_pushButton.setIcon(icon4)
        self.m_stop_all_pushButton.setIconSize(QSize(35, 35))
        self.m_stop_all_pushButton.setAutoDefault(False)
        self.m_stop_all_pushButton.setFlat(False)
        self.test_weight_y_label_2 = QLabel(self.test_page)
        self.test_weight_y_label_2.setObjectName(u"test_weight_y_label_2")
        self.test_weight_y_label_2.setGeometry(QRect(260, 20, 51, 50))
        self.test_weight_y_label_2.setFont(font3)
        self.test_weight_y_label_2.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_weight_y_label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_weight_y_label_3 = QLabel(self.test_page)
        self.test_weight_y_label_3.setObjectName(u"test_weight_y_label_3")
        self.test_weight_y_label_3.setGeometry(QRect(560, 20, 51, 50))
        self.test_weight_y_label_3.setFont(font3)
        self.test_weight_y_label_3.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_weight_y_label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_2_line_2 = QFrame(self.test_page)
        self.test_2_line_2.setObjectName(u"test_2_line_2")
        self.test_2_line_2.setGeometry(QRect(310, 20, 2, 50))
        self.test_2_line_2.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.test_2_line_2.setFrameShape(QFrame.Shape.VLine)
        self.test_2_line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.test_2_line_4 = QFrame(self.test_page)
        self.test_2_line_4.setObjectName(u"test_2_line_4")
        self.test_2_line_4.setGeometry(QRect(610, 20, 2, 50))
        self.test_2_line_4.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.test_2_line_4.setFrameShape(QFrame.Shape.VLine)
        self.test_2_line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.test_dis_y_unit_label = QLabel(self.test_page)
        self.test_dis_y_unit_label.setObjectName(u"test_dis_y_unit_label")
        self.test_dis_y_unit_label.setGeometry(QRect(890, 20, 51, 50))
        self.test_dis_y_unit_label.setFont(font3)
        self.test_dis_y_unit_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_dis_y_unit_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_dis_x_unit_label = QLabel(self.test_page)
        self.test_dis_x_unit_label.setObjectName(u"test_dis_x_unit_label")
        self.test_dis_x_unit_label.setGeometry(QRect(1240, 20, 51, 50))
        self.test_dis_x_unit_label.setFont(font3)
        self.test_dis_x_unit_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_dis_x_unit_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.test_2_line_5 = QFrame(self.test_page)
        self.test_2_line_5.setObjectName(u"test_2_line_5")
        self.test_2_line_5.setGeometry(QRect(940, 20, 2, 50))
        self.test_2_line_5.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.test_2_line_5.setFrameShape(QFrame.Shape.VLine)
        self.test_2_line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.test_manual_control_checkBox = QCheckBox(self.test_page)
        self.test_manual_control_checkBox.setObjectName(u"test_manual_control_checkBox")
        self.test_manual_control_checkBox.setGeometry(QRect(1120, 490, 210, 70))
        font5 = QFont()
        font5.setFamilies([u"TH Niramit AS"])
        font5.setPointSize(20)
        font5.setBold(True)
        self.test_manual_control_checkBox.setFont(font5)
        self.test_manual_control_checkBox.setMouseTracking(False)
        self.test_manual_control_checkBox.setTabletTracking(True)
        self.test_manual_control_checkBox.setAcceptDrops(False)
        self.test_manual_control_checkBox.setAutoFillBackground(False)
        self.test_manual_control_checkBox.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_manual_control_checkBox.setIconSize(QSize(16, 16))
        self.test_manual_control_checkBox.setCheckable(True)
        self.test_manual_control_checkBox.setChecked(False)
        self.test_manual_control_checkBox.setTristate(False)
        self.stackedWidget.addWidget(self.test_page)
        self.test_background_label.raise_()
        self.test_cyclic_round_label.raise_()
        self.test_dis_y_unit_label.raise_()
        self.test_weight_y_label_3.raise_()
        self.test_weight_y_label_2.raise_()
        self.test_weight_y_label.raise_()
        self.test_weight_x_label.raise_()
        self.test_dis_x_label.raise_()
        self.test_dis_y_label.raise_()
        self.test_weight_y_lineEdit.raise_()
        self.test_weight_x_lineEdit.raise_()
        self.test_dis_y_lineEdit.raise_()
        self.test_dis_x_lineEdit.raise_()
        self.test_1line.raise_()
        self.grap_frame.raise_()
        self.test_start_pushButton.raise_()
        self.test_stop_pushButton.raise_()
        self.test_clear_pushButton.raise_()
        self.test_save_pushButton.raise_()
        self.test_cyclic_round_lineEdit.raise_()
        self.m_up_pushButton.raise_()
        self.m_down_pushButton.raise_()
        self.m_out_pushButton.raise_()
        self.m_in_pushButton.raise_()
        self.m_stop_all_pushButton.raise_()
        self.test_2_line_2.raise_()
        self.test_2_line_4.raise_()
        self.test_dis_x_unit_label.raise_()
        self.test_2_line_5.raise_()
        self.test_manual_control_checkBox.raise_()
        self.setting_page = QWidget()
        self.setting_page.setObjectName(u"setting_page")
        self.setting_page.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.st_label = QLabel(self.setting_page)
        self.st_label.setObjectName(u"st_label")
        self.st_label.setGeometry(QRect(-20, -10, 1311, 721))
        self.st_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_pwm_x_label = QLabel(self.setting_page)
        self.st_pwm_x_label.setObjectName(u"st_pwm_x_label")
        self.st_pwm_x_label.setGeometry(QRect(530, 90, 91, 31))
        self.st_pwm_x_label.setFont(font3)
        self.st_pwm_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_pwm_x_lineEdit = QLineEdit(self.setting_page)
        self.st_pwm_x_lineEdit.setObjectName(u"st_pwm_x_lineEdit")
        self.st_pwm_x_lineEdit.setGeometry(QRect(640, 80, 121, 41))
        self.st_pwm_x_lineEdit.setFont(font5)
        self.st_pwm_x_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_pwm_y_label = QLabel(self.setting_page)
        self.st_pwm_y_label.setObjectName(u"st_pwm_y_label")
        self.st_pwm_y_label.setGeometry(QRect(530, 160, 91, 31))
        self.st_pwm_y_label.setFont(font3)
        self.st_pwm_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_pwm_y_lineEdit = QLineEdit(self.setting_page)
        self.st_pwm_y_lineEdit.setObjectName(u"st_pwm_y_lineEdit")
        self.st_pwm_y_lineEdit.setGeometry(QRect(640, 150, 121, 41))
        self.st_pwm_y_lineEdit.setFont(font5)
        self.st_pwm_y_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_weight_x_label = QLabel(self.setting_page)
        self.st_weight_x_label.setObjectName(u"st_weight_x_label")
        self.st_weight_x_label.setGeometry(QRect(10, 250, 261, 51))
        self.st_weight_x_label.setFont(font3)
        self.st_weight_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_weight_x_lineEdit = QLineEdit(self.setting_page)
        self.st_weight_x_lineEdit.setObjectName(u"st_weight_x_lineEdit")
        self.st_weight_x_lineEdit.setGeometry(QRect(260, 250, 121, 41))
        self.st_weight_x_lineEdit.setFont(font5)
        self.st_weight_x_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_limit_weight_x_lineEdit = QLineEdit(self.setting_page)
        self.st_limit_weight_x_lineEdit.setObjectName(u"st_limit_weight_x_lineEdit")
        self.st_limit_weight_x_lineEdit.setGeometry(QRect(640, 250, 121, 41))
        self.st_limit_weight_x_lineEdit.setFont(font5)
        self.st_limit_weight_x_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_limit_weight_y_lineEdit = QLineEdit(self.setting_page)
        self.st_limit_weight_y_lineEdit.setObjectName(u"st_limit_weight_y_lineEdit")
        self.st_limit_weight_y_lineEdit.setGeometry(QRect(640, 320, 121, 41))
        self.st_limit_weight_y_lineEdit.setFont(font5)
        self.st_limit_weight_y_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_limit_weight_y_label = QLabel(self.setting_page)
        self.st_limit_weight_y_label.setObjectName(u"st_limit_weight_y_label")
        self.st_limit_weight_y_label.setGeometry(QRect(470, 320, 141, 51))
        self.st_limit_weight_y_label.setFont(font3)
        self.st_limit_weight_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_limit_weight_x_label = QLabel(self.setting_page)
        self.st_limit_weight_x_label.setObjectName(u"st_limit_weight_x_label")
        self.st_limit_weight_x_label.setGeometry(QRect(470, 250, 141, 51))
        self.st_limit_weight_x_label.setFont(font3)
        self.st_limit_weight_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_limit_distance_y_lineEdit = QLineEdit(self.setting_page)
        self.st_limit_distance_y_lineEdit.setObjectName(u"st_limit_distance_y_lineEdit")
        self.st_limit_distance_y_lineEdit.setGeometry(QRect(640, 490, 121, 41))
        self.st_limit_distance_y_lineEdit.setFont(font5)
        self.st_limit_distance_y_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_limit_distance_x_lineEdit = QLineEdit(self.setting_page)
        self.st_limit_distance_x_lineEdit.setObjectName(u"st_limit_distance_x_lineEdit")
        self.st_limit_distance_x_lineEdit.setGeometry(QRect(640, 420, 121, 41))
        self.st_limit_distance_x_lineEdit.setFont(font5)
        self.st_limit_distance_x_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_limit_distance_x_label = QLabel(self.setting_page)
        self.st_limit_distance_x_label.setObjectName(u"st_limit_distance_x_label")
        self.st_limit_distance_x_label.setGeometry(QRect(490, 420, 131, 51))
        self.st_limit_distance_x_label.setFont(font3)
        self.st_limit_distance_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_limit_distance_y_label = QLabel(self.setting_page)
        self.st_limit_distance_y_label.setObjectName(u"st_limit_distance_y_label")
        self.st_limit_distance_y_label.setGeometry(QRect(490, 490, 141, 51))
        self.st_limit_distance_y_label.setFont(font3)
        self.st_limit_distance_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_line_2 = QFrame(self.setting_page)
        self.st_line_2.setObjectName(u"st_line_2")
        self.st_line_2.setGeometry(QRect(0, 220, 850, 2))
        self.st_line_2.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_2.setFrameShape(QFrame.Shape.HLine)
        self.st_line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_line_3 = QFrame(self.setting_page)
        self.st_line_3.setObjectName(u"st_line_3")
        self.st_line_3.setGeometry(QRect(0, 60, 850, 2))
        self.st_line_3.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_3.setFrameShape(QFrame.Shape.HLine)
        self.st_line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_line_4 = QFrame(self.setting_page)
        self.st_line_4.setObjectName(u"st_line_4")
        self.st_line_4.setGeometry(QRect(0, 390, 850, 2))
        self.st_line_4.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_4.setFrameShape(QFrame.Shape.HLine)
        self.st_line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_line_5 = QFrame(self.setting_page)
        self.st_line_5.setObjectName(u"st_line_5")
        self.st_line_5.setGeometry(QRect(0, 560, 850, 2))
        self.st_line_5.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_5.setFrameShape(QFrame.Shape.HLine)
        self.st_line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_line_6 = QFrame(self.setting_page)
        self.st_line_6.setObjectName(u"st_line_6")
        self.st_line_6.setGeometry(QRect(850, 60, 2, 502))
        self.st_line_6.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_6.setFrameShape(QFrame.Shape.VLine)
        self.st_line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_save_pushButton = QPushButton(self.setting_page)
        self.st_save_pushButton.setObjectName(u"st_save_pushButton")
        self.st_save_pushButton.setGeometry(QRect(880, 150, 181, 71))
        self.st_save_pushButton.setFont(font4)
        self.st_save_pushButton.setStyleSheet(u"background:rgb(170, 255, 0)")
        self.st_config_pushButton = QPushButton(self.setting_page)
        self.st_config_pushButton.setObjectName(u"st_config_pushButton")
        self.st_config_pushButton.setGeometry(QRect(880, 60, 181, 71))
        self.st_config_pushButton.setFont(font4)
        self.st_config_pushButton.setStyleSheet(u"background:rgb(115, 174, 253)")
        self.st_line_7 = QFrame(self.setting_page)
        self.st_line_7.setObjectName(u"st_line_7")
        self.st_line_7.setGeometry(QRect(460, 60, 2, 500))
        self.st_line_7.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_7.setFrameShape(QFrame.Shape.VLine)
        self.st_line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_cyclic_lineEdit = QLineEdit(self.setting_page)
        self.st_cyclic_lineEdit.setObjectName(u"st_cyclic_lineEdit")
        self.st_cyclic_lineEdit.setGeometry(QRect(260, 80, 121, 41))
        self.st_cyclic_lineEdit.setFont(font5)
        self.st_cyclic_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_cyclic_label = QLabel(self.setting_page)
        self.st_cyclic_label.setObjectName(u"st_cyclic_label")
        self.st_cyclic_label.setGeometry(QRect(170, 90, 91, 31))
        self.st_cyclic_label.setFont(font3)
        self.st_cyclic_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.LX_Port_comboBox = QComboBox(self.setting_page)
        self.LX_Port_comboBox.addItem("")
        self.LX_Port_comboBox.setObjectName(u"LX_Port_comboBox")
        self.LX_Port_comboBox.setGeometry(QRect(30, 620, 151, 51))
        self.LX_Port_comboBox.setFont(font4)
        self.LY_Port_comboBox = QComboBox(self.setting_page)
        self.LY_Port_comboBox.addItem("")
        self.LY_Port_comboBox.setObjectName(u"LY_Port_comboBox")
        self.LY_Port_comboBox.setGeometry(QRect(250, 620, 151, 51))
        self.LY_Port_comboBox.setFont(font4)
        self.LDVT_Port_comboBox = QComboBox(self.setting_page)
        self.LDVT_Port_comboBox.addItem("")
        self.LDVT_Port_comboBox.setObjectName(u"LDVT_Port_comboBox")
        self.LDVT_Port_comboBox.setGeometry(QRect(460, 620, 151, 51))
        self.LDVT_Port_comboBox.setFont(font4)
        self.con_port_pushButton = QPushButton(self.setting_page)
        self.con_port_pushButton.setObjectName(u"con_port_pushButton")
        self.con_port_pushButton.setGeometry(QRect(1070, 560, 181, 51))
        self.con_port_pushButton.setFont(font5)
        self.con_port_pushButton.setStyleSheet(u"background:rgb(170, 255, 0)")
        self.dis_port_pushButton = QPushButton(self.setting_page)
        self.dis_port_pushButton.setObjectName(u"dis_port_pushButton")
        self.dis_port_pushButton.setGeometry(QRect(1070, 620, 181, 51))
        self.dis_port_pushButton.setFont(font5)
        self.dis_port_pushButton.setStyleSheet(u"background:rgb(252, 65, 54)")
        self.comport_LX_label = QLabel(self.setting_page)
        self.comport_LX_label.setObjectName(u"comport_LX_label")
        self.comport_LX_label.setGeometry(QRect(50, 570, 161, 51))
        self.comport_LX_label.setFont(font3)
        self.comport_LX_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.comport_LY_label = QLabel(self.setting_page)
        self.comport_LY_label.setObjectName(u"comport_LY_label")
        self.comport_LY_label.setGeometry(QRect(270, 570, 161, 51))
        self.comport_LY_label.setFont(font3)
        self.comport_LY_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.comport_LVDT_label = QLabel(self.setting_page)
        self.comport_LVDT_label.setObjectName(u"comport_LVDT_label")
        self.comport_LVDT_label.setGeometry(QRect(470, 570, 161, 51))
        self.comport_LVDT_label.setFont(font3)
        self.comport_LVDT_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_Area_lineEdit = QLineEdit(self.setting_page)
        self.st_Area_lineEdit.setObjectName(u"st_Area_lineEdit")
        self.st_Area_lineEdit.setGeometry(QRect(260, 150, 121, 41))
        self.st_Area_lineEdit.setFont(font5)
        self.st_Area_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_Area_label = QLabel(self.setting_page)
        self.st_Area_label.setObjectName(u"st_Area_label")
        self.st_Area_label.setGeometry(QRect(170, 150, 51, 41))
        self.st_Area_label.setFont(font3)
        self.st_Area_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_Area_unit_label = QLabel(self.setting_page)
        self.st_Area_unit_label.setObjectName(u"st_Area_unit_label")
        self.st_Area_unit_label.setGeometry(QRect(400, 160, 51, 31))
        self.st_Area_unit_label.setFont(font3)
        self.st_Area_unit_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_cyclic_round_label = QLabel(self.setting_page)
        self.st_cyclic_round_label.setObjectName(u"st_cyclic_round_label")
        self.st_cyclic_round_label.setGeometry(QRect(390, 90, 81, 31))
        self.st_cyclic_round_label.setFont(font3)
        self.st_cyclic_round_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_K_label = QLabel(self.setting_page)
        self.st_K_label.setObjectName(u"st_K_label")
        self.st_K_label.setGeometry(QRect(210, 410, 31, 51))
        self.st_K_label.setFont(font3)
        self.st_K_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_K_lineEdit = QLineEdit(self.setting_page)
        self.st_K_lineEdit.setObjectName(u"st_K_lineEdit")
        self.st_K_lineEdit.setGeometry(QRect(260, 410, 121, 41))
        self.st_K_lineEdit.setFont(font5)
        self.st_K_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.st_limit_weight_x_unit_label = QLabel(self.setting_page)
        self.st_limit_weight_x_unit_label.setObjectName(u"st_limit_weight_x_unit_label")
        self.st_limit_weight_x_unit_label.setGeometry(QRect(780, 250, 41, 51))
        self.st_limit_weight_x_unit_label.setFont(font3)
        self.st_limit_weight_x_unit_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_limit_weight_y_unit_label = QLabel(self.setting_page)
        self.st_limit_weight_y_unit_label.setObjectName(u"st_limit_weight_y_unit_label")
        self.st_limit_weight_y_unit_label.setGeometry(QRect(780, 320, 41, 51))
        self.st_limit_weight_y_unit_label.setFont(font3)
        self.st_limit_weight_y_unit_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_limit_distance_x_unit_label = QLabel(self.setting_page)
        self.st_limit_distance_x_unit_label.setObjectName(u"st_limit_distance_x_unit_label")
        self.st_limit_distance_x_unit_label.setGeometry(QRect(780, 420, 51, 51))
        self.st_limit_distance_x_unit_label.setFont(font3)
        self.st_limit_distance_x_unit_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_limit_distance_y_unit_label = QLabel(self.setting_page)
        self.st_limit_distance_y_unit_label.setObjectName(u"st_limit_distance_y_unit_label")
        self.st_limit_distance_y_unit_label.setGeometry(QRect(780, 490, 51, 51))
        self.st_limit_distance_y_unit_label.setFont(font3)
        self.st_limit_distance_y_unit_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_monotonic_radioButton = QRadioButton(self.setting_page)
        self.test_monotonic_radioButton.setObjectName(u"test_monotonic_radioButton")
        self.test_monotonic_radioButton.setGeometry(QRect(1110, 60, 181, 61))
        self.test_monotonic_radioButton.setFont(font)
        self.test_monotonic_radioButton.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_cyclic_radioButton = QRadioButton(self.setting_page)
        self.test_cyclic_radioButton.setObjectName(u"test_cyclic_radioButton")
        self.test_cyclic_radioButton.setGeometry(QRect(1110, 120, 181, 61))
        self.test_cyclic_radioButton.setFont(font)
        self.test_cyclic_radioButton.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_line_8 = QFrame(self.setting_page)
        self.st_line_8.setObjectName(u"st_line_8")
        self.st_line_8.setGeometry(QRect(1110, 60, 181, 2))
        self.st_line_8.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_8.setFrameShape(QFrame.Shape.HLine)
        self.st_line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_line_9 = QFrame(self.setting_page)
        self.st_line_9.setObjectName(u"st_line_9")
        self.st_line_9.setGeometry(QRect(1110, 180, 181, 2))
        self.st_line_9.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_9.setFrameShape(QFrame.Shape.HLine)
        self.st_line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_line_10 = QFrame(self.setting_page)
        self.st_line_10.setObjectName(u"st_line_10")
        self.st_line_10.setGeometry(QRect(1110, 60, 2, 120))
        self.st_line_10.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_10.setFrameShape(QFrame.Shape.VLine)
        self.st_line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_line_11 = QFrame(self.setting_page)
        self.st_line_11.setObjectName(u"st_line_11")
        self.st_line_11.setGeometry(QRect(1110, 120, 181, 2))
        self.st_line_11.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.st_line_11.setFrameShape(QFrame.Shape.HLine)
        self.st_line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.st_test_label = QLabel(self.setting_page)
        self.st_test_label.setObjectName(u"st_test_label")
        self.st_test_label.setGeometry(QRect(140, 10, 191, 51))
        self.st_test_label.setFont(font3)
        self.st_test_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_machine_label = QLabel(self.setting_page)
        self.st_machine_label.setObjectName(u"st_machine_label")
        self.st_machine_label.setGeometry(QRect(590, 10, 191, 51))
        self.st_machine_label.setFont(font3)
        self.st_machine_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_rpm_x_label = QLabel(self.setting_page)
        self.st_rpm_x_label.setObjectName(u"st_rpm_x_label")
        self.st_rpm_x_label.setGeometry(QRect(770, 90, 81, 31))
        self.st_rpm_x_label.setFont(font3)
        self.st_rpm_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_rpm_y_label = QLabel(self.setting_page)
        self.st_rpm_y_label.setObjectName(u"st_rpm_y_label")
        self.st_rpm_y_label.setGeometry(QRect(770, 160, 81, 31))
        self.st_rpm_y_label.setFont(font3)
        self.st_rpm_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_weight_y_label = QLabel(self.setting_page)
        self.st_weight_y_label.setObjectName(u"st_weight_y_label")
        self.st_weight_y_label.setGeometry(QRect(10, 320, 261, 51))
        self.st_weight_y_label.setFont(font3)
        self.st_weight_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_weight_y_lineEdit = QLineEdit(self.setting_page)
        self.st_weight_y_lineEdit.setObjectName(u"st_weight_y_lineEdit")
        self.st_weight_y_lineEdit.setGeometry(QRect(260, 320, 121, 41))
        self.st_weight_y_lineEdit.setFont(font5)
        self.st_weight_y_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.motor_Port_x_comboBox = QComboBox(self.setting_page)
        self.motor_Port_x_comboBox.addItem("")
        self.motor_Port_x_comboBox.setObjectName(u"motor_Port_x_comboBox")
        self.motor_Port_x_comboBox.setGeometry(QRect(670, 620, 151, 51))
        self.motor_Port_x_comboBox.setFont(font4)
        self.comport_motor_x_label = QLabel(self.setting_page)
        self.comport_motor_x_label.setObjectName(u"comport_motor_x_label")
        self.comport_motor_x_label.setGeometry(QRect(680, 570, 141, 51))
        self.comport_motor_x_label.setFont(font3)
        self.comport_motor_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_kn_x_label = QLabel(self.setting_page)
        self.st_kn_x_label.setObjectName(u"st_kn_x_label")
        self.st_kn_x_label.setGeometry(QRect(400, 250, 51, 51))
        self.st_kn_x_label.setFont(font3)
        self.st_kn_x_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.st_kn_y_label = QLabel(self.setting_page)
        self.st_kn_y_label.setObjectName(u"st_kn_y_label")
        self.st_kn_y_label.setGeometry(QRect(400, 320, 41, 51))
        self.st_kn_y_label.setFont(font3)
        self.st_kn_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.test_k_set_pushButton = QPushButton(self.setting_page)
        self.test_k_set_pushButton.setObjectName(u"test_k_set_pushButton")
        self.test_k_set_pushButton.setGeometry(QRect(260, 460, 121, 51))
        self.test_k_set_pushButton.setFont(font5)
        self.test_k_set_pushButton.setStyleSheet(u"background:rgb(206, 223, 255)")
        self.comport_motor_y_label = QLabel(self.setting_page)
        self.comport_motor_y_label.setObjectName(u"comport_motor_y_label")
        self.comport_motor_y_label.setGeometry(QRect(890, 570, 141, 51))
        self.comport_motor_y_label.setFont(font3)
        self.comport_motor_y_label.setStyleSheet(u"background:rgb(255, 255, 222)")
        self.motor_Port_y_comboBox = QComboBox(self.setting_page)
        self.motor_Port_y_comboBox.addItem("")
        self.motor_Port_y_comboBox.setObjectName(u"motor_Port_y_comboBox")
        self.motor_Port_y_comboBox.setGeometry(QRect(880, 620, 151, 51))
        self.motor_Port_y_comboBox.setFont(font4)
        self.stackedWidget.addWidget(self.setting_page)
        self.st_label.raise_()
        self.st_cyclic_label.raise_()
        self.st_cyclic_round_label.raise_()
        self.st_rpm_x_label.raise_()
        self.st_rpm_y_label.raise_()
        self.st_machine_label.raise_()
        self.st_test_label.raise_()
        self.st_pwm_x_label.raise_()
        self.st_pwm_x_lineEdit.raise_()
        self.st_pwm_y_label.raise_()
        self.st_pwm_y_lineEdit.raise_()
        self.st_weight_x_label.raise_()
        self.st_weight_x_lineEdit.raise_()
        self.st_limit_weight_x_lineEdit.raise_()
        self.st_limit_weight_y_lineEdit.raise_()
        self.st_limit_weight_y_label.raise_()
        self.st_limit_weight_x_label.raise_()
        self.st_limit_distance_y_lineEdit.raise_()
        self.st_limit_distance_x_lineEdit.raise_()
        self.st_limit_distance_x_label.raise_()
        self.st_limit_distance_y_label.raise_()
        self.st_line_2.raise_()
        self.st_line_3.raise_()
        self.st_line_4.raise_()
        self.st_line_5.raise_()
        self.st_line_6.raise_()
        self.st_save_pushButton.raise_()
        self.st_config_pushButton.raise_()
        self.st_line_7.raise_()
        self.st_cyclic_lineEdit.raise_()
        self.LX_Port_comboBox.raise_()
        self.LY_Port_comboBox.raise_()
        self.LDVT_Port_comboBox.raise_()
        self.con_port_pushButton.raise_()
        self.dis_port_pushButton.raise_()
        self.comport_LX_label.raise_()
        self.comport_LY_label.raise_()
        self.comport_LVDT_label.raise_()
        self.st_Area_lineEdit.raise_()
        self.st_Area_label.raise_()
        self.st_Area_unit_label.raise_()
        self.st_K_label.raise_()
        self.st_K_lineEdit.raise_()
        self.st_limit_weight_x_unit_label.raise_()
        self.st_limit_weight_y_unit_label.raise_()
        self.st_limit_distance_x_unit_label.raise_()
        self.st_limit_distance_y_unit_label.raise_()
        self.test_monotonic_radioButton.raise_()
        self.test_cyclic_radioButton.raise_()
        self.st_line_8.raise_()
        self.st_line_9.raise_()
        self.st_line_10.raise_()
        self.st_line_11.raise_()
        self.st_weight_y_label.raise_()
        self.st_weight_y_lineEdit.raise_()
        self.motor_Port_x_comboBox.raise_()
        self.comport_motor_x_label.raise_()
        self.st_kn_x_label.raise_()
        self.st_kn_y_label.raise_()
        self.test_k_set_pushButton.raise_()
        self.comport_motor_y_label.raise_()
        self.motor_Port_y_comboBox.raise_()
        self.background_label = QLabel(self.centralwidget)
        self.background_label.setObjectName(u"background_label")
        self.background_label.setGeometry(QRect(-50, 0, 1501, 801))
        self.background_label.setAutoFillBackground(False)
        self.background_label.setStyleSheet(u"border-image: url(picture/background.png)")
        MAIN.setCentralWidget(self.centralwidget)
        self.background_label.raise_()
        self.home_pushButton.raise_()
        self.calibrate_pushButton.raise_()
        self.test_pushButton.raise_()
        self.setting_pushButton.raise_()
        self.stackedWidget.raise_()

        self.retranslateUi(MAIN)

        self.stackedWidget.setCurrentIndex(1)
        self.m_up_pushButton.setDefault(False)
        self.m_down_pushButton.setDefault(False)
        self.m_out_pushButton.setDefault(False)
        self.m_in_pushButton.setDefault(False)
        self.m_stop_all_pushButton.setDefault(False)


        QMetaObject.connectSlotsByName(MAIN)
    # setupUi

    def retranslateUi(self, MAIN):
        MAIN.setWindowTitle(QCoreApplication.translate("MAIN", u"MAIN", None))
        self.home_pushButton.setText(QCoreApplication.translate("MAIN", u"\u0e2b\u0e19\u0e49\u0e32\u0e2b\u0e25\u0e31\u0e01", None))
        self.calibrate_pushButton.setText(QCoreApplication.translate("MAIN", u"CALIBRATE", None))
        self.test_pushButton.setText(QCoreApplication.translate("MAIN", u"TEST", None))
        self.setting_pushButton.setText(QCoreApplication.translate("MAIN", u"\u0e15\u0e31\u0e49\u0e07\u0e04\u0e48\u0e32", None))
        self.message_1_label.setText(QCoreApplication.translate("MAIN", u"WELLCOME TO MACHINE ", None))
        self.message_2_label.setText(QCoreApplication.translate("MAIN", u"CONTROLLER", None))
        self.picture_label.setText("")
        self.r_weight_y_label.setText(QCoreApplication.translate("MAIN", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e41\u0e01\u0e19 Y", None))
        self.r_weight_x_label.setText(QCoreApplication.translate("MAIN", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e41\u0e01\u0e19 x", None))
        self.r_weight_y_lineEdit.setText("")
        self.r_weight_x_lineEdit.setText("")
        self.cl_background_labe.setText("")
        self.r_kg_y_label.setText(QCoreApplication.translate("MAIN", u"KG", None))
        self.r_kg_x__label.setText(QCoreApplication.translate("MAIN", u"KG", None))
        self.c_weight_x_label.setText(QCoreApplication.translate("MAIN", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e41\u0e01\u0e19 x", None))
        self.c_kg_x__label.setText(QCoreApplication.translate("MAIN", u"KG", None))
        self.c_kg_y_label.setText(QCoreApplication.translate("MAIN", u"KG", None))
        self.c_weight_y_lineEdit.setText("")
        self.c_weight_y_label.setText(QCoreApplication.translate("MAIN", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e41\u0e01\u0e19 Y", None))
        self.c_weight_x_lineEdit.setText("")
        self.r_weight_label.setText(QCoreApplication.translate("MAIN", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e1b\u0e31\u0e08\u0e08\u0e38\u0e1a\u0e31\u0e19", None))
        self.c_weight_label.setText(QCoreApplication.translate("MAIN", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e17\u0e35\u0e48\u0e43\u0e2a\u0e48", None))
        self.cl_set_zero_pushButton.setText(QCoreApplication.translate("MAIN", u"SET ZERO", None))
        self.cl_calibrate_pushButton.setText(QCoreApplication.translate("MAIN", u"CALIBRATE", None))
        self.dis_set_zero_x_unit_label.setText(QCoreApplication.translate("MAIN", u"MM", None))
        self.dis_set_zero_y_unit_label.setText(QCoreApplication.translate("MAIN", u"MM", None))
        self.dis_set_zero_x_label.setText(QCoreApplication.translate("MAIN", u"\u0e23\u0e30\u0e22\u0e30\u0e41\u0e01\u0e19 x", None))
        self.save_offset_pushButton.setText(QCoreApplication.translate("MAIN", u"save", None))
        self.dis_set_zero_y_label.setText(QCoreApplication.translate("MAIN", u"\u0e23\u0e30\u0e22\u0e30\u0e41\u0e01\u0e19 Y", None))
        self.dis_set_offset_y_lineEdit.setText("")
        self.dis_set_offset_x_lineEdit.setText("")
        self.r_weight_label_2.setText(QCoreApplication.translate("MAIN", u"\u0e01\u0e33\u0e2b\u0e19\u0e14\u0e04\u0e48\u0e32 offset", None))
        self.set_offset_pushButton.setText(QCoreApplication.translate("MAIN", u"set offset", None))
        self.set_zero_dx_pushButton.setText(QCoreApplication.translate("MAIN", u"set zero DX", None))
        self.set_zero_dy_pushButton.setText(QCoreApplication.translate("MAIN", u"set zero DY", None))
        self.r_weight_label_3.setText(QCoreApplication.translate("MAIN", u"SET ZERO DY,DX", None))
        self.test_background_label.setText("")
        self.test_weight_y_label.setText(QCoreApplication.translate("MAIN", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01 Y", None))
        self.test_weight_x_label.setText(QCoreApplication.translate("MAIN", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01 X", None))
        self.test_dis_x_label.setText(QCoreApplication.translate("MAIN", u"Dis Horizontal", None))
        self.test_dis_y_label.setText(QCoreApplication.translate("MAIN", u"Dis Vertical", None))
        self.test_weight_y_lineEdit.setText("")
        self.test_weight_x_lineEdit.setText("")
        self.test_dis_y_lineEdit.setText("")
        self.test_dis_x_lineEdit.setText("")
        self.test_start_pushButton.setText(QCoreApplication.translate("MAIN", u"START", None))
        self.test_stop_pushButton.setText(QCoreApplication.translate("MAIN", u"STOP", None))
        self.test_clear_pushButton.setText(QCoreApplication.translate("MAIN", u"CLEAR", None))
        self.test_save_pushButton.setText(QCoreApplication.translate("MAIN", u"SAVE", None))
        self.test_cyclic_round_label.setText(QCoreApplication.translate("MAIN", u"\u0e08\u0e33\u0e19\u0e27\u0e19\u0e23\u0e2d\u0e1a", None))
        self.test_cyclic_round_lineEdit.setText("")
        self.m_up_pushButton.setText("")
        self.m_down_pushButton.setText("")
        self.m_out_pushButton.setText("")
        self.m_in_pushButton.setText("")
        self.m_stop_all_pushButton.setText("")
        self.test_weight_y_label_2.setText(QCoreApplication.translate("MAIN", u"kPa", None))
        self.test_weight_y_label_3.setText(QCoreApplication.translate("MAIN", u"kPa", None))
        self.test_dis_y_unit_label.setText(QCoreApplication.translate("MAIN", u"mm", None))
        self.test_dis_x_unit_label.setText(QCoreApplication.translate("MAIN", u"mm", None))
        self.test_manual_control_checkBox.setText(QCoreApplication.translate("MAIN", u"Manual Control", None))
        self.st_label.setText("")
        self.st_pwm_x_label.setText(QCoreApplication.translate("MAIN", u"SPEED Y", None))
        self.st_pwm_y_label.setText(QCoreApplication.translate("MAIN", u"SPEED X", None))
        self.st_weight_x_label.setText(QCoreApplication.translate("MAIN", u"\u0e2b\u0e19\u0e48\u0e27\u0e22\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e17\u0e35\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23 X", None))
        self.st_limit_weight_x_lineEdit.setText("")
        self.st_limit_weight_y_lineEdit.setText("")
        self.st_limit_weight_y_label.setText(QCoreApplication.translate("MAIN", u"\u0e2b\u0e19\u0e48\u0e27\u0e22 Y MAX", None))
        self.st_limit_weight_x_label.setText(QCoreApplication.translate("MAIN", u"\u0e2b\u0e19\u0e48\u0e27\u0e22 X MAX", None))
        self.st_limit_distance_y_lineEdit.setText("")
        self.st_limit_distance_x_lineEdit.setText("")
        self.st_limit_distance_x_label.setText(QCoreApplication.translate("MAIN", u"\u0e25\u0e34\u0e21\u0e34\u0e15\u0e23\u0e30\u0e22\u0e30 X", None))
        self.st_limit_distance_y_label.setText(QCoreApplication.translate("MAIN", u"\u0e25\u0e34\u0e21\u0e34\u0e15\u0e23\u0e30\u0e22\u0e30 Y", None))
        self.st_save_pushButton.setText(QCoreApplication.translate("MAIN", u"SAVE", None))
        self.st_config_pushButton.setText(QCoreApplication.translate("MAIN", u"CONFIG", None))
        self.st_cyclic_label.setText(QCoreApplication.translate("MAIN", u"CYCLIC", None))
        self.LX_Port_comboBox.setItemText(0, QCoreApplication.translate("MAIN", u"None", None))

        self.LY_Port_comboBox.setItemText(0, QCoreApplication.translate("MAIN", u"None", None))

        self.LDVT_Port_comboBox.setItemText(0, QCoreApplication.translate("MAIN", u"None", None))

        self.con_port_pushButton.setText(QCoreApplication.translate("MAIN", u"CONNECT", None))
        self.dis_port_pushButton.setText(QCoreApplication.translate("MAIN", u"DISCONNECT", None))
        self.comport_LX_label.setText(QCoreApplication.translate("MAIN", u"Load X Port", None))
        self.comport_LY_label.setText(QCoreApplication.translate("MAIN", u"Load Y Port", None))
        self.comport_LVDT_label.setText(QCoreApplication.translate("MAIN", u"LVDT Port", None))
        self.st_Area_label.setText(QCoreApplication.translate("MAIN", u"\u0e1e\u0e37\u0e49\u0e19\u0e17\u0e35\u0e48", None))
        self.st_Area_unit_label.setText(QCoreApplication.translate("MAIN", u"m2", None))
        self.st_cyclic_round_label.setText(QCoreApplication.translate("MAIN", u"Round", None))
        self.st_K_label.setText(QCoreApplication.translate("MAIN", u" K", None))
        self.st_K_lineEdit.setText("")
        self.st_limit_weight_x_unit_label.setText(QCoreApplication.translate("MAIN", u"kPa", None))
        self.st_limit_weight_y_unit_label.setText(QCoreApplication.translate("MAIN", u"kPa", None))
        self.st_limit_distance_x_unit_label.setText(QCoreApplication.translate("MAIN", u"mm", None))
        self.st_limit_distance_y_unit_label.setText(QCoreApplication.translate("MAIN", u"mm", None))
        self.test_monotonic_radioButton.setText(QCoreApplication.translate("MAIN", u"Monotonic", None))
        self.test_cyclic_radioButton.setText(QCoreApplication.translate("MAIN", u"Cyclic", None))
        self.st_test_label.setText(QCoreApplication.translate("MAIN", u"\u0e15\u0e31\u0e49\u0e07\u0e04\u0e48\u0e32\u0e43\u0e19\u0e01\u0e32\u0e23\u0e17\u0e14\u0e2a\u0e2d\u0e1a", None))
        self.st_machine_label.setText(QCoreApplication.translate("MAIN", u"\u0e15\u0e31\u0e49\u0e07\u0e04\u0e48\u0e32\u0e40\u0e04\u0e23\u0e37\u0e48\u0e2d\u0e07", None))
        self.st_rpm_x_label.setText(QCoreApplication.translate("MAIN", u"0-100%", None))
        self.st_rpm_y_label.setText(QCoreApplication.translate("MAIN", u"0-100%", None))
        self.st_weight_y_label.setText(QCoreApplication.translate("MAIN", u"\u0e2b\u0e19\u0e48\u0e27\u0e22\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01\u0e17\u0e35\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23 Y", None))
        self.motor_Port_x_comboBox.setItemText(0, QCoreApplication.translate("MAIN", u"None", None))

        self.comport_motor_x_label.setText(QCoreApplication.translate("MAIN", u"Motor X Port", None))
        self.st_kn_x_label.setText(QCoreApplication.translate("MAIN", u"kPa", None))
        self.st_kn_y_label.setText(QCoreApplication.translate("MAIN", u"kPa", None))
        self.test_k_set_pushButton.setText(QCoreApplication.translate("MAIN", u"K SET", None))
        self.comport_motor_y_label.setText(QCoreApplication.translate("MAIN", u"Motor Y Port", None))
        self.motor_Port_y_comboBox.setItemText(0, QCoreApplication.translate("MAIN", u"None", None))

        self.background_label.setText(QCoreApplication.translate("MAIN", u"TextLabel", None))
    # retranslateUi

