from PySide6.QtWidgets import QMainWindow
from view.main_frame import Ui_MAIN

class MainFrame(QMainWindow,Ui_MAIN):
    def __init__(self, parent=None):
        super(MainFrame, self).__init__(parent)
        self.setupUi(self)

    def show_home_page(self):
        self.stackedWidget.setCurrentIndex(0)
        self.show()

    def show_calibate_page(self):
        self.stackedWidget.setCurrentIndex(1)
        self.show()

    def show_test_page(self):
        self.stackedWidget.setCurrentIndex(2)
        self.show()

    def show_setting_page(self):
        self.stackedWidget.setCurrentIndex(3)
        self.show()

    def setup_programe_ui(self):
        self.cl_calibrate_pushButton.setEnabled(False)
        self.cl_set_zero_pushButton.setEnabled(False)
        self.c_weight_x_lineEdit.setEnabled(False)
        self.c_weight_y_lineEdit.setEnabled(False)
        self.st_cyclic_lineEdit.setEnabled(False)
        self.test_cyclic_round_lineEdit.setEnabled(False)
        self.st_weight_x_lineEdit.setEnabled(False)
        self.test_monotonic_radioButton.setEnabled(False)
        self.test_cyclic_radioButton.setEnabled(False)
        self.test_cyclic_round_lineEdit.setEnabled(False)
        self.st_pwm_x_lineEdit.setEnabled(False)
        self.st_pwm_y_lineEdit.setEnabled(False)
        self.st_save_pushButton.setEnabled(False)
        self.st_Area_lineEdit.setEnabled(False)
        self.st_limit_distance_x_lineEdit.setEnabled(False)
        self.st_limit_distance_y_lineEdit.setEnabled(False)
        self.st_limit_weight_y_lineEdit.setEnabled(False)
        self.st_limit_weight_x_lineEdit.setEnabled(False)
        self.st_config_pushButton.setEnabled(True)
        self.st_save_pushButton.setEnabled(False)
        self.save_offset_pushButton.setEnabled(False)
        self.cl_calibrate_pushButton.setStyleSheet("background-color:gray;")
        self.cl_set_zero_pushButton.setStyleSheet("background-color:gray;")
        self.c_weight_x_lineEdit.setStyleSheet("background-color:gray;")
        self.c_weight_y_lineEdit.setStyleSheet("background-color:gray;")
        self.st_cyclic_lineEdit.setStyleSheet("background-color:gray;")
        self.test_cyclic_round_lineEdit.setStyleSheet("background-color:gray;")
        self.st_weight_x_lineEdit.setStyleSheet("background-color:gray;")
        self.test_monotonic_radioButton.setStyleSheet("background-color:gray;")
        self.test_cyclic_radioButton.setStyleSheet("background-color:gray;")
        self.test_cyclic_round_lineEdit.setStyleSheet("background-color:gray;")
        self.st_pwm_x_lineEdit.setStyleSheet("background-color:gray;")
        self.st_pwm_y_lineEdit.setStyleSheet("background-color:gray;")
        self.st_save_pushButton.setStyleSheet("background-color:gray;")
        self.st_Area_lineEdit.setStyleSheet("background-color:gray;")
        self.st_limit_distance_x_lineEdit.setStyleSheet("background-color:gray;")
        self.st_limit_distance_y_lineEdit.setStyleSheet("background-color:gray;")
        self.st_limit_weight_y_lineEdit.setStyleSheet("background-color:gray;")
        self.st_limit_weight_x_lineEdit.setStyleSheet("background-color:gray;")
        self.st_config_pushButton.setStyleSheet("background-color:rgb(115, 174, 253);")
        self.st_save_pushButton.setStyleSheet("background-color:gray;")
        self.save_offset_pushButton.setStyleSheet("background-color:gray;")
        
    def con_to_port(self):
        self.con_port_pushButton.setEnabled(False)
        self.dis_port_pushButton.setEnabled(True)
        self.LX_Port_comboBox.setEnabled(False)
        self.LY_Port_comboBox.setEnabled(False)
        self.LDVT_Port_comboBox.setEnabled(False)
        self.motor_Port_x_comboBox.setEnabled(False)
        self.motor_Port_y_comboBox.setEnabled(False)
        self.st_save_pushButton.setEnabled(False)
        
        self.con_port_pushButton.setStyleSheet("background-color:gray;")
        self.dis_port_pushButton.setStyleSheet("background-color:rgb(252, 65, 54);")
        self.LX_Port_comboBox.setStyleSheet("background-color:gray;")
        self.LY_Port_comboBox.setStyleSheet("background-color:gray;")
        self.LDVT_Port_comboBox.setStyleSheet("background-color:gray;")
        self.motor_Port_x_comboBox.setStyleSheet("background-color:gray;")
        self.motor_Port_y_comboBox.setStyleSheet("background-color:gray;")
        self.st_save_pushButton.setStyleSheet("background-color:gray;")
        
    def dis_con_to_port(self):
        self.con_port_pushButton.setEnabled(True)
        self.dis_port_pushButton.setEnabled(False)
        self.LX_Port_comboBox.setEnabled(True)
        self.LY_Port_comboBox.setEnabled(True)
        self.LDVT_Port_comboBox.setEnabled(True)
        self.motor_Port_x_comboBox.setEnabled(True)
        self.motor_Port_y_comboBox.setEnabled(True)
        self.st_save_pushButton.setEnabled(True)
        
        self.con_port_pushButton.setStyleSheet("background-color:rgb(170, 255, 0);")
        self.dis_port_pushButton.setStyleSheet("background-color:gray;")
        self.LX_Port_comboBox.setStyleSheet("background-color:white;")
        self.LY_Port_comboBox.setStyleSheet("background-color:white;")
        self.LDVT_Port_comboBox.setStyleSheet("background-color:white;")
        self.motor_Port_x_comboBox.setStyleSheet("background-color:white;")
        self.motor_Port_y_comboBox.setStyleSheet("background-color:white;")
        self.st_save_pushButton.setStyleSheet("background-color:rgb(170, 255, 0);")
        
    def config_parameter(self):
        self.st_Area_lineEdit.setEnabled(True)
        self.st_limit_distance_x_lineEdit.setEnabled(True)
        self.st_limit_distance_y_lineEdit.setEnabled(True)
        self.st_limit_weight_y_lineEdit.setEnabled(True)
        self.st_limit_weight_x_lineEdit.setEnabled(True)
        self.st_config_pushButton.setEnabled(False)
        self.st_save_pushButton.setEnabled(True)
        
        self.st_Area_lineEdit.setStyleSheet("background-color:white;")
        self.st_limit_distance_x_lineEdit.setStyleSheet("background-color:white;")
        self.st_limit_distance_y_lineEdit.setStyleSheet("background-color:white;")
        self.st_limit_weight_y_lineEdit.setStyleSheet("background-color:white;")
        self.st_limit_weight_x_lineEdit.setStyleSheet("background-color:white;")
        self.st_config_pushButton.setStyleSheet("background-color:gray;")
        self.st_save_pushButton.setStyleSheet("background-color:rgb(170, 255, 0);")
        
    def save_parameter(self):
        self.st_Area_lineEdit.setEnabled(False)
        self.st_limit_distance_x_lineEdit.setEnabled(False)
        self.st_limit_distance_y_lineEdit.setEnabled(False)
        self.st_limit_weight_y_lineEdit.setEnabled(False)
        self.st_limit_weight_x_lineEdit.setEnabled(False)
        self.st_config_pushButton.setEnabled(True)
        self.st_save_pushButton.setEnabled(False)
        
        self.st_Area_lineEdit.setStyleSheet("background-color:gray;")
        self.st_limit_distance_x_lineEdit.setStyleSheet("background-color:gray;")
        self.st_limit_distance_y_lineEdit.setStyleSheet("background-color:gray;")
        self.st_limit_weight_y_lineEdit.setStyleSheet("background-color:gray;")
        self.st_limit_weight_x_lineEdit.setStyleSheet("background-color:gray;")
        self.st_config_pushButton.setStyleSheet("background-color:rgb(115, 174, 253);")
        self.st_save_pushButton.setStyleSheet("background-color:gray;")
        
    def enable_manual_control(self):
        self.m_in_pushButton.setEnabled(True)
        self.m_out_pushButton.setEnabled(True)
        self.m_up_pushButton.setEnabled(True)
        self.m_down_pushButton.setEnabled(True)
        self.m_stop_all_pushButton.setEnabled(True)
        self.m_in_pushButton.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.m_out_pushButton.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.m_up_pushButton.setStyleSheet("background-color:rgb(85, 255, 0)")
        self.m_down_pushButton.setStyleSheet("background-color:rgb(85, 255, 0)")
        self.m_stop_all_pushButton.setStyleSheet("background-color:rgb(255, 145, 137)")
        
    def disable_manual_control(self):
        self.m_in_pushButton.setEnabled(False)
        self.m_out_pushButton.setEnabled(False)
        self.m_up_pushButton.setEnabled(False)
        self.m_down_pushButton.setEnabled(False)
        self.m_stop_all_pushButton.setEnabled(False)
        self.m_in_pushButton.setStyleSheet("background-color:gray")
        self.m_out_pushButton.setStyleSheet("background-color:gray")
        self.m_up_pushButton.setStyleSheet("background-color:gray")
        self.m_down_pushButton.setStyleSheet("background-color:gray")
        self.m_stop_all_pushButton.setStyleSheet("background-color:gray")